// ── Greeting system — 8 time slots, 100+ entries each ────────────────────────
// Slots: earlyMorning | morning | lateMorning | midday | afternoon | evening | night | lateNight
// Line 1: time-aware greeting (may include {name})
// Line 2: biblical encouragement (no {name})

type G = [string, string]; // [line1, line2]

const EARLY_MORNING: G[] = [
  ["Good morning, {name}.", "God's mercies are new with the sunrise."],
  ["The sun is rising, {name}.", "Every dawn is a gift from God's hand."],
  ["An early start, {name}.", "Give the first moments of the day to prayer."],
  ["The morning is still quiet, {name}.", "This stillness is a gift — use it well."],
  ["You are up early, {name}.", "The Lord meets those who seek Him at dawn."],
  ["The world is waking, {name}.", "God has been awake through every hour of the night."],
  ["Sunrise is here, {name}.", "His compassions fail not — they are new this morning."],
  ["A new day is beginning, {name}.", "Walk in wisdom from the very first hour."],
  ["Good morning, {name}.", "Seek God before the day demands your attention."],
  ["The dawn has come, {name}.", "God's faithfulness is as sure as the sunrise."],
  ["The morning belongs to God, {name}.", "Begin it with thanks."],
  ["Rise with gratitude, {name}.", "The Lord has sustained you through the night."],
  ["The early hour is a treasure, {name}.", "Spend it in God's presence."],
  ["The sky is brightening, {name}.", "God's glory fills the heavens."],
  ["A fresh morning is here, {name}.", "Let Scripture shape the hours ahead."],
  ["Good morning, {name}.", "Prayer opens the day better than anything else."],
  ["The sun is coming up, {name}.", "So is the opportunity to honor God today."],
  ["An early morning, {name}.", "God's purposes never sleep."],
  ["Morning has broken, {name}.", "Praise the Maker of light and darkness."],
  ["The day is just beginning, {name}.", "Lay it before God in prayer."],
  ["You have risen early, {name}.", "Use this hour to meet God in His Word."],
  ["The morning is fresh, {name}.", "God's truth is fresher still."],
  ["A quiet morning, {name}.", "Bring a quiet heart before a great God."],
  ["The stars are fading, {name}.", "God's promises are undimmed by day or night."],
  ["Good morning, {name}.", "Let the Word of God be the first voice you hear."],
  ["The early morning is yours, {name}.", "Offer it back to the One who gave it."],
  ["The horizon is brightening, {name}.", "God reigns over every new beginning."],
  ["Morning is here, {name}.", "The Lord is worthy of worship in the early hours."],
  ["Up before the world, {name}.", "The Lord is already at work."],
  ["The day is young, {name}.", "Ask God for wisdom before it grows old."],
  ["Good morning, {name}.", "The heavens declare God's glory — look up."],
  ["An early hour, {name}.", "God's grace is sufficient for all the hours that follow."],
  ["The birds are singing, {name}.", "Creation praises its Maker every morning."],
  ["The morning light is arriving, {name}.", "Christ is the Light no darkness can overcome."],
  ["A new day dawns, {name}.", "Walk in the fear of the Lord today."],
  ["Good morning, {name}.", "Give thanks — you have been given another day."],
  ["The night has passed, {name}.", "God kept watch through every dark hour."],
  ["You are awake early, {name}.", "The Lord rewards those who seek Him diligently."],
  ["A stillness fills the morning, {name}.", "Be still and know that He is God."],
  ["Good morning, {name}.", "Open the Scriptures — God still speaks."],
  ["The first light has come, {name}.", "Christ is the Light of the world."],
  ["A new morning, {name}.", "Every day is another act of God's patience and grace."],
  ["The morning is a mercy, {name}.", "Receive it with humility and thanks."],
  ["The sun is rising over the earth, {name}.", "God's sovereignty is over all of it."],
  ["Good morning, {name}.", "The fear of the Lord is the beginning of wisdom."],
  ["An early awakening, {name}.", "Ask God what He would have you do today."],
  ["The morning air is cool, {name}.", "So is the refreshment of God's Word."],
  ["A quiet start to the day, {name}.", "God is not silent — He speaks in Scripture."],
  ["Good morning, {name}.", "Seek first the kingdom of God — all else follows."],
  ["The morning is a reminder, {name}.", "God's mercies are not exhausted by our failures."],
  ["Sunrise finds you well, {name}.", "The Lord who made the sun knows your name."],
  ["The world stirs early, {name}.", "God's truth does not change with the hour."],
  ["Good morning, {name}.", "Pray before the day fills your mind with noise."],
  ["A fresh start, {name}.", "God's patience makes every morning a fresh start."],
  ["The morning is here, {name}.", "Worship is not only for Sunday — give glory now."],
  ["An early morning, {name}.", "Let your first thoughts turn to the Lord."],
  ["Good morning, {name}.", "The resurrection of Christ means every morning holds hope."],
  ["The sun breaks through, {name}.", "God's purposes break through every obstacle."],
  ["You are awake, {name}.", "So is the Lord — He never slumbers nor sleeps."],
  ["Good morning, {name}.", "Cast your anxieties on God before they grow heavy."],
  ["The early morning is quiet, {name}.", "Find God in the silence before the noise begins."],
  ["A new day begins, {name}.", "Walk humbly with your God this day."],
  ["Good morning, {name}.", "Consider what the Lord has done — praise is fitting."],
  ["The morning has come, {name}.", "God's steadfast love was present before the sunrise."],
  ["Rise and give thanks, {name}.", "A grateful heart honors the Giver of all things."],
  ["The day is dawning, {name}.", "God holds this day in His hands."],
  ["Good morning, {name}.", "Ask God for grace — He gives generously to all who ask."],
  ["An early morning, {name}.", "Scripture in the morning is bread for the whole day."],
  ["The night has ended, {name}.", "God sustained you through the dark — praise Him."],
  ["Good morning, {name}.", "The Lord your God is mighty — trust Him for the day."],
  ["The morning is a canvas, {name}.", "Let God's Word paint the strokes that matter."],
  ["You are awake early, {name}.", "Bring your plans to God before you begin them."],
  ["A good morning to you, {name}.", "God's goodness is not exhausted — it waits for you today."],
  ["The dawn greets you, {name}.", "Greet it with prayer."],
  ["Good morning, {name}.", "God is not far — He is as close as a sincere prayer."],
  ["The morning is God's, {name}.", "And so are you — remember that today."],
  ["A new sunrise, {name}.", "The Creator of the sun is worthy of your worship."],
  ["Good morning, {name}.", "Let the Word of God dwell richly in you today."],
  ["The early hours are here, {name}.", "Give them to prayer and Scripture before the day runs away."],
  ["The morning star has risen, {name}.", "Christ is the same yesterday, today, and forever."],
  ["Good morning, {name}.", "God has purposes for this day — walk faithfully into them."],
  ["A stillness remains, {name}.", "Use it to hear the still, small voice of God."],
  ["Morning is upon you, {name}.", "Consider God's faithfulness from yesterday."],
  ["Good morning, {name}.", "Repentance is always available — so is forgiveness."],
  ["The horizon glows, {name}.", "God's glory is not limited to sunrises."],
  ["An early start, {name}.", "Begin with gratitude and end with the same."],
  ["Good morning, {name}.", "God knows your name — and your needs — before you ask."],
  ["The morning is cool and quiet, {name}.", "God is near to all who call upon Him."],
  ["A new day has arrived, {name}.", "The Lord's purposes for it are already set."],
  ["Good morning, {name}.", "The gospel is still good news — receive it today."],
  ["The sun climbs upward, {name}.", "God's faithfulness climbs no higher and falls no lower."],
  ["You rise early, {name}.", "The Lord rewards those who diligently seek Him."],
  ["Good morning, {name}.", "Humility opens the door to God's grace."],
  ["The morning dew is on the ground, {name}.", "God's mercies fall just as fresh."],
  ["A new morning is here, {name}.", "Nothing from yesterday has surprised God."],
  ["Good morning, {name}.", "Christ is risen — and that makes every morning different."],
  ["The early light has come, {name}.", "Let your heart be light as well."],
  ["A fresh morning greets you, {name}.", "God is not tired of being faithful."],
];

const MORNING: G[] = [
  ["Good morning, {name}.", "Walk in wisdom as the day unfolds."],
  ["A new day is underway, {name}.", "Seek first the kingdom of God."],
  ["The morning is moving along, {name}.", "Fix your heart on what is eternal."],
  ["Good morning, {name}.", "God's Word is a lamp — let it light your steps today."],
  ["The day has begun, {name}.", "Bring your plans to God before the day brings surprises."],
  ["Good morning, {name}.", "Prayer is always the right place to start."],
  ["The morning is here, {name}.", "God's faithfulness runs from sunrise to sunset."],
  ["A good morning to you, {name}.", "Consider the grace that brought you to this day."],
  ["Good morning, {name}.", "The Lord reigns — walk into this day without fear."],
  ["The day is open before you, {name}.", "Ask God what He would have you do with it."],
  ["Good morning, {name}.", "Let gratitude be the first note of the day."],
  ["Morning greetings, {name}.", "God is worthy of your first thoughts."],
  ["The morning is here, {name}.", "Seek the Lord while He may be found."],
  ["A morning for God's glory, {name}.", "Let every word and deed honor Him."],
  ["Good morning, {name}.", "The Scriptures await — wisdom is found in them."],
  ["The day is ahead of you, {name}.", "God knows every hour of it."],
  ["Good morning, {name}.", "Cast your anxieties on God — He cares for you."],
  ["The morning sun is up, {name}.", "So is the Savior — He rose and He reigns."],
  ["A fresh morning, {name}.", "Every mercy God gives is undeserved — give thanks."],
  ["Good morning, {name}.", "God's providence governs this day — trust it."],
  ["The morning greets you, {name}.", "Greet it with a heart turned toward God."],
  ["A new morning, {name}.", "Walk in the Spirit throughout this day."],
  ["Good morning, {name}.", "The name of the Lord is a strong tower."],
  ["The day is here, {name}.", "God has prepared good works for you to walk in."],
  ["Good morning, {name}.", "Take up the Word — it is sharper than any sword."],
  ["Morning is here, {name}.", "Let your speech be seasoned with grace today."],
  ["A new morning has arrived, {name}.", "God's purposes are moving forward."],
  ["Good morning, {name}.", "Worship is not a feeling — it is a choice. Choose it."],
  ["The morning is underway, {name}.", "Bring a humble heart into every conversation."],
  ["Good morning, {name}.", "The Lord hears every sincere prayer you offer."],
  ["A good morning, {name}.", "Seek wisdom from above — it is given generously."],
  ["The morning calls, {name}.", "Answer it with prayer and gratitude."],
  ["Good morning, {name}.", "Nothing in this day is outside God's knowledge."],
  ["The day begins, {name}.", "Let it begin with the Lord."],
  ["Good morning, {name}.", "God's patience is a mercy — do not take it for granted."],
  ["The morning is bright, {name}.", "Christ is brighter — He is the Light of the world."],
  ["A morning to be grateful, {name}.", "Count even the small mercies."],
  ["Good morning, {name}.", "The fear of the Lord is the foundation of wisdom."],
  ["The day is young, {name}.", "Use it while you have it."],
  ["Good morning, {name}.", "Repentance keeps the heart clean — practice it daily."],
  ["Morning greetings, {name}.", "The Lord's steadfast love never ceases."],
  ["The morning is yours to steward, {name}.", "Steward it well."],
  ["Good morning, {name}.", "Every good gift in this day comes from above."],
  ["The day has opened, {name}.", "Open your heart to meet it with God."],
  ["Good morning, {name}.", "Let Scripture be the lens through which you see today."],
  ["The morning is a gift, {name}.", "Open it with care."],
  ["Good morning, {name}.", "God is not surprised by what this day holds."],
  ["A fine morning, {name}.", "The Lord who made it is worthy of praise."],
  ["Good morning, {name}.", "Walk in love today — the greatest commandment is still in force."],
  ["The morning awaits, {name}.", "Begin it on your knees if you can."],
  ["Good morning, {name}.", "God's sovereignty is a comfort, not a burden."],
  ["The day opens wide, {name}.", "Walk into it with confidence in God."],
  ["Good morning, {name}.", "The Holy Spirit is a helper — ask for help today."],
  ["A morning to walk wisely, {name}.", "Wisdom begins with fearing God."],
  ["Good morning, {name}.", "Let your words today build up rather than tear down."],
  ["The morning is here, {name}.", "God's promises are as firm as they were yesterday."],
  ["Good morning, {name}.", "There is no wisdom apart from the Word of God."],
  ["The day is fresh, {name}.", "Bring a fresh heart to God's old truths."],
  ["Good morning, {name}.", "Prayer is not a religious duty — it is access to God."],
  ["The morning is moving, {name}.", "Do not let it pass without turning your thoughts to God."],
  ["Good morning, {name}.", "God's kingdom is not shaken by what shakes the world."],
  ["A morning of opportunities, {name}.", "Ask God how to use them well."],
  ["Good morning, {name}.", "Contentment is a discipline — practice it today."],
  ["The day is beginning, {name}.", "Begin it with the end in mind — eternity."],
  ["Good morning, {name}.", "The cross is the greatest act of love in history."],
  ["Morning is here, {name}.", "Consider who God is before considering what you need."],
  ["Good morning, {name}.", "The Word of God stands forever — read it today."],
  ["The morning is an opportunity, {name}.", "Seize it for God's glory."],
  ["Good morning, {name}.", "Do not lean on your own understanding today — trust God."],
  ["The day stretches ahead, {name}.", "God sees every hour of it."],
  ["Good morning, {name}.", "Humility is not weakness — it is the path to grace."],
  ["A morning well spent, {name}.", "Begins with God and ends in gratitude."],
  ["Good morning, {name}.", "Give thanks in all circumstances — God commands it for your good."],
  ["The morning is steady, {name}.", "God is steadier still."],
  ["Good morning, {name}.", "Christ's yoke is easy — take it up today."],
  ["A new day, {name}.", "God's mercies are more than yesterday's failures."],
  ["Good morning, {name}.", "Look to Christ — He is the author and finisher of faith."],
  ["The morning is well underway, {name}.", "Walk in it with God."],
  ["Good morning, {name}.", "Ask for grace — it is given freely to the humble."],
  ["The day is open, {name}.", "God's purposes are working through it."],
  ["Good morning, {name}.", "Nothing surprises God — walk with that confidence today."],
  ["Morning greets you, {name}.", "Let gratitude greet it back."],
  ["Good morning, {name}.", "The resurrection of Christ changes everything about today."],
  ["A morning to be still, {name}.", "And know that He is God."],
  ["Good morning, {name}.", "God is patient — and His patience is a gift."],
  ["The morning is clear, {name}.", "So is the call to seek God first."],
  ["Good morning, {name}.", "Meditate on God's Word — it will steady you."],
  ["The day has begun, {name}.", "Begin it with prayer."],
  ["Good morning, {name}.", "The Lord your God is with you wherever you go."],
  ["A new morning, {name}.", "A new opportunity to walk in God's truth."],
  ["Good morning, {name}.", "God's glory is the reason for everything — keep that in view."],
  ["The morning is here, {name}.", "Give it to God and trust Him with the outcome."],
  ["Good morning, {name}.", "Scripture is living and active — open it."],
  ["A morning like every morning, {name}.", "And yet God's mercies are entirely new."],
  ["Good morning, {name}.", "Pray for those around you before you see them today."],
  ["The morning calls for focus, {name}.", "Fix your eyes on what is true and good."],
  ["Good morning, {name}.", "God's grace is available for this specific day."],
  ["The day is begun, {name}.", "May it bring glory to God."],
];

const LATE_MORNING: G[] = [
  ["The morning is moving along, {name}.", "Keep your thoughts fixed on what is true."],
  ["Lunch is approaching, {name}.", "Feed your soul as well as your body."],
  ["The morning is nearly done, {name}.", "Take a moment to give God thanks."],
  ["Late morning, {name}.", "God's faithfulness has carried the day this far."],
  ["The hours are passing, {name}.", "Spend some of them in prayer."],
  ["The morning is winding down, {name}.", "God's purposes are not winding down with it."],
  ["Late morning finds you, {name}.", "Pause before the afternoon arrives."],
  ["The morning is slipping by, {name}.", "Make sure God has been part of it."],
  ["Late morning, {name}.", "A good time to pause and pray."],
  ["The morning is nearly over, {name}.", "The Lord has been faithful through it."],
  ["Late morning is here, {name}.", "Consider what God has already provided today."],
  ["The morning is passing, {name}.", "Pause and fix your mind on things above."],
  ["Late morning greets you, {name}.", "God's truth is just as firm as it was at sunrise."],
  ["The morning is moving forward, {name}.", "Walk with God through every hour."],
  ["Late morning, {name}.", "Cast your cares on God before lunch."],
  ["The morning hours are almost spent, {name}.", "Spend a few moments in gratitude."],
  ["Late morning is upon you, {name}.", "God is near to all who call on Him."],
  ["The morning draws to a close, {name}.", "The Lord has governed every minute of it."],
  ["Late morning, {name}.", "Wisdom is worth more than the tasks on your list."],
  ["The morning is getting along, {name}.", "Take a quiet moment before the midday rush."],
  ["Late morning finds you well, {name}.", "God's grace has carried you to this hour."],
  ["The morning is almost at midday, {name}.", "Pause and give thanks for what God has provided."],
  ["Late morning, {name}.", "God's Word has not changed since you woke."],
  ["The morning is nearly noon, {name}.", "A good time to lift a brief prayer."],
  ["Late morning is here, {name}.", "Remember that Christ is the same through every hour."],
  ["The morning moves quickly, {name}.", "Eternity does not — keep the end in mind."],
  ["Late morning, {name}.", "God's kingdom does not depend on your busyness."],
  ["The morning is winding toward noon, {name}.", "Rest briefly in the Lord before pressing on."],
  ["Late morning greets you, {name}.", "The Lord's counsel stands — seek it today."],
  ["The morning has been given to you, {name}.", "Return thanks to the Giver."],
  ["Late morning, {name}.", "All that matters eternally is built on God's truth."],
  ["The morning is drawing on, {name}.", "God's mercy draws on too — without end."],
  ["Late morning finds you, {name}.", "Take a breath and pray before the day presses harder."],
  ["The morning is still here, {name}.", "God is still near."],
  ["Late morning, {name}.", "Quiet your heart before noon arrives."],
  ["The day is picking up, {name}.", "God's faithfulness keeps pace with every hour."],
  ["Late morning is upon you, {name}.", "Let Scripture anchor what the afternoon cannot shake."],
  ["The morning passes, {name}.", "God does not."],
  ["Late morning, {name}.", "A brief prayer is better than a long worry."],
  ["The morning hours linger, {name}.", "Use them wisely."],
  ["Late morning greets you, {name}.", "God's grace is more than sufficient for today."],
  ["The morning is almost midday, {name}.", "Let your heart be settled in the Lord."],
  ["Late morning, {name}.", "God's purposes are at work even when you are not watching."],
  ["The morning moves on, {name}.", "Walk with God through every change of hour."],
  ["Late morning is here, {name}.", "Nothing today has gone unnoticed by God."],
  ["The morning light holds, {name}.", "God's promises hold firmer still."],
  ["Late morning, {name}.", "Consider one thing God has done for you and give thanks."],
  ["The morning is fading into noon, {name}.", "Give God the glory of this passing hour."],
  ["Late morning greets you well, {name}.", "The Lord is good to those who seek Him."],
  ["The morning has served you, {name}.", "Serve God with the rest of the day."],
  ["Late morning, {name}.", "Seek wisdom before you need it."],
  ["The morning is winding down, {name}.", "God's strength for the afternoon is already prepared."],
  ["Late morning finds you, {name}.", "Remember what matters most before the day grows loud."],
  ["The morning is nearly past, {name}.", "Not a moment of it was outside God's notice."],
  ["Late morning, {name}.", "Christ's words are bread for every hour of the day."],
  ["The morning draws near to noon, {name}.", "Let your heart draw near to God."],
  ["Late morning is upon you, {name}.", "Ask God for wisdom for the hours ahead."],
  ["The morning lingers, {name}.", "So does God's steadfast love."],
  ["Late morning, {name}.", "Pray briefly — even a few words lifted to God matter."],
  ["The morning is closing, {name}.", "The Lord remains open to all who call on Him."],
  ["Late morning greets you, {name}.", "God has been faithful since the sun rose."],
  ["The morning hours are precious, {name}.", "Treat the remaining ones with care."],
  ["Late morning, {name}.", "God's Word will outlast the busyness of today."],
  ["The morning moves toward noon, {name}.", "Move toward God before it arrives."],
  ["Late morning is here, {name}.", "Consider the Lord's goodness in the hours already past."],
  ["The morning is still with you, {name}.", "Be still before God while you can."],
  ["Late morning, {name}.", "Bring your midday plans to God first."],
  ["The morning rounds toward noon, {name}.", "God's sovereignty rounds through every hour."],
  ["Late morning finds you busy, {name}.", "Even busy hands can have a praying heart."],
  ["The morning is ending, {name}.", "The Lord's purposes are not."],
  ["Late morning greets you, {name}.", "God's grace sustains you through the busiest hours."],
  ["The morning presses on, {name}.", "Press on toward what is godly and true."],
  ["Late morning, {name}.", "Consider what the Lord has done — praise rises from gratitude."],
  ["The morning is almost gone, {name}.", "Take a moment before it is."],
  ["Late morning is upon you, {name}.", "A humble heart is never too busy for God."],
  ["The morning rounds to noon, {name}.", "God's faithfulness is just as present at midday."],
  ["Late morning, {name}.", "God's purposes move at the right pace — trust His timing."],
  ["The morning is heading toward its end, {name}.", "Lift a brief prayer before it goes."],
  ["Late morning greets you well, {name}.", "The Lord is a refuge in every hour."],
  ["The morning concludes, {name}.", "God never concludes His care over you."],
  ["Late morning, {name}.", "Let wisdom govern your words for the rest of the day."],
  ["The morning is still bright, {name}.", "So is the truth of God's Word."],
  ["Late morning finds you, {name}.", "Take a moment to acknowledge God's goodness."],
  ["The morning is drawing to its close, {name}.", "Draw close to God before it does."],
  ["Late morning, {name}.", "The Lord's counsel will guide you rightly if you seek it."],
  ["The morning nearly gives way to noon, {name}.", "Give thanks for every hour God has given."],
  ["Late morning is here, {name}.", "God's patience with us is a great mercy."],
  ["The morning light is steady, {name}.", "God's love is steadier."],
  ["Late morning, {name}.", "The fear of the Lord is the beginning of all wisdom."],
  ["The morning comes to its end, {name}.", "God's faithfulness does not."],
  ["Late morning greets you, {name}.", "Keep the eternal in view as the temporal presses."],
  ["The morning is nearly spent, {name}.", "Spend a moment with God before it is."],
  ["Late morning, {name}.", "God's mercies are new every morning — and still fresh now."],
  ["The morning closes, {name}.", "The Lord remains constant."],
  ["Late morning is upon you, {name}.", "A prayer before noon is a good investment."],
  ["The morning finishes, {name}.", "God's faithfulness has carried every minute of it."],
  ["Late morning greets you, {name}.", "Consider the goodness of God in what the morning held."],
  ["The morning is its last hour, {name}.", "The Lord is still first."],
  ["Late morning, {name}.", "Gratitude prepares the heart for whatever afternoon brings."],
];

const MIDDAY: G[] = [
  ["It's lunchtime, {name}.", "Take time to nourish both body and soul."],
  ["Pause for a moment, {name}.", "God's Word is worth your attention."],
  ["The midday hour is here, {name}.", "Give God a moment before the afternoon begins."],
  ["It's noon, {name}.", "Rest briefly in the Lord before pressing on."],
  ["Lunchtime is here, {name}.", "Man does not live by bread alone."],
  ["The middle of the day, {name}.", "Let your thoughts return to Christ."],
  ["Midday is upon you, {name}.", "God is just as near at noon as He was at sunrise."],
  ["It's lunchtime, {name}.", "Refresh your body — and your spirit while you're at it."],
  ["The midday pause, {name}.", "A good time to cast your cares on God."],
  ["Noon is here, {name}.", "Consider what God has already provided this day."],
  ["The day is at its center, {name}.", "God is at the center of all things."],
  ["Lunchtime, {name}.", "Give thanks before you eat — God is the Giver of every good thing."],
  ["Midday greets you, {name}.", "God's faithfulness has carried the morning and will carry the afternoon."],
  ["The noon hour is here, {name}.", "Take a breath and give God thanks."],
  ["It's midday, {name}.", "God's purposes are at work in the middle of ordinary days."],
  ["Lunchtime, {name}.", "God sees every hour — even the unremarkable ones."],
  ["The midday hour, {name}.", "Let your heart be at rest — God is in control."],
  ["Noon finds you, {name}.", "Let it find you in prayer as well."],
  ["Midday is here, {name}.", "The Lord reigns through every hour of the day."],
  ["The middle of the day, {name}.", "Pause and give thanks for what the morning held."],
  ["Lunchtime, {name}.", "Feed the inner man as well — spend time in God's Word."],
  ["The noon hour, {name}.", "Bring your afternoon to God before it begins."],
  ["Midday, {name}.", "God's grace is available for the second half of the day."],
  ["Noon is upon you, {name}.", "Rest briefly in the God who never rests from caring for you."],
  ["Lunchtime, {name}.", "Cast your cares on God — He is able to carry them."],
  ["The midday hour is here, {name}.", "Take a moment to be still before God."],
  ["Midday greets you, {name}.", "God's truth does not change between morning and afternoon."],
  ["Noon, {name}.", "A perfect time to lift a prayer for the afternoon ahead."],
  ["The middle of the day, {name}.", "God's sovereignty spans every hour of it."],
  ["Lunchtime is upon you, {name}.", "A grateful heart is a healthy heart."],
  ["Midday, {name}.", "The Lord is a refuge at noon as much as midnight."],
  ["The noon hour has arrived, {name}.", "Consider the Lord's goodness from the morning hours."],
  ["It's lunchtime, {name}.", "Let gratitude rise before anything else."],
  ["Midday finds you, {name}.", "God has not lost sight of you this day."],
  ["Noon is here, {name}.", "Wisdom is worth pursuing in the middle of the day."],
  ["The midday hour, {name}.", "God's promises are still true at noon."],
  ["Lunchtime, {name}.", "Let prayer be part of your midday break."],
  ["Midday, {name}.", "The Word of God is bread for every hour — not just morning."],
  ["Noon is upon you, {name}.", "Turn your heart to God before the afternoon takes hold."],
  ["The middle of the day, {name}.", "God's faithfulness runs from dawn to dusk — and beyond."],
  ["Lunchtime, {name}.", "Consider how God has provided — for this meal and beyond."],
  ["Midday has come, {name}.", "The Lord is still at work in the middle of ordinary hours."],
  ["The noon hour is here, {name}.", "Pause and acknowledge God in the center of the day."],
  ["Midday greets you, {name}.", "Walk in wisdom for the hours that remain."],
  ["Noon, {name}.", "God's steadfast love does not take a lunch break."],
  ["The midday pause, {name}.", "Use it to draw near to God."],
  ["Lunchtime is here, {name}.", "Give thanks for provision — God is a generous Father."],
  ["Midday is here, {name}.", "Whatever the morning held, the afternoon is in God's hands."],
  ["Noon has arrived, {name}.", "The Lord who governs the morning governs the afternoon too."],
  ["The middle of the day, {name}.", "Let your heart be refreshed by God's truth."],
  ["Lunchtime, {name}.", "Nourish your body and your soul with what God has given."],
  ["Midday, {name}.", "God's care for you does not pause at noon."],
  ["The noon hour, {name}.", "A perfect time to give the afternoon to God."],
  ["Midday finds you, {name}.", "Find God in return."],
  ["Noon is here, {name}.", "God's goodness is worth a moment of reflection."],
  ["The midday hour is upon you, {name}.", "God is worthy of praise in the middle of the day."],
  ["Lunchtime, {name}.", "Let Scripture be part of your break if you can."],
  ["Midday greets you, {name}.", "The Lord's counsel is worth seeking before the afternoon."],
  ["Noon, {name}.", "Repentance and thanksgiving are always appropriate at noon."],
  ["The middle of the day, {name}.", "God's glory is the reason for every hour."],
  ["Lunchtime is upon you, {name}.", "Give thanks — it honors God and helps the heart."],
  ["Midday is here, {name}.", "The Lord's faithfulness is new at noon just as it is at dawn."],
  ["Noon has come, {name}.", "Take a quiet moment before the afternoon presses."],
  ["The midday hour, {name}.", "God is not distant in the middle of a busy day."],
  ["Midday, {name}.", "Pray before eating — God is the source of every good gift."],
  ["Noon finds you in the middle of the day, {name}.", "Find God in the middle of it too."],
  ["Lunchtime, {name}.", "God's grace sustains the busy and the still alike."],
  ["The midday hour is here, {name}.", "God's truth is still worth your attention at noon."],
  ["Midday greets you, {name}.", "Walk through the afternoon in the fear of the Lord."],
  ["Noon, {name}.", "The Lord's Word is a foundation — return to it even at midday."],
  ["The middle of the day, {name}.", "Let the middle of your heart be full of gratitude."],
  ["Lunchtime, {name}.", "God's patience is a great mercy — do not presume upon it."],
  ["Midday has arrived, {name}.", "God's purposes have arrived alongside it."],
  ["The noon hour is here, {name}.", "A good time to pray for those you will encounter today."],
  ["Midday, {name}.", "God's goodness is not limited to the morning."],
  ["Noon is upon you, {name}.", "Lift a prayer before the afternoon takes you where it will."],
  ["The midday pause, {name}.", "Rest briefly in the unchanging character of God."],
  ["Lunchtime, {name}.", "The Lord provides for body and soul — give thanks."],
  ["Midday greets you, {name}.", "God has not left His throne since this morning."],
  ["Noon, {name}.", "A humble prayer at noon is worth more than a long worry."],
  ["The middle of the day, {name}.", "What God has begun, He will faithfully complete."],
  ["Lunchtime is here, {name}.", "Pause and consider the Lord's goodness."],
  ["Midday is upon you, {name}.", "God's sovereignty governs the hours you see and the ones you don't."],
  ["The noon hour, {name}.", "Let wisdom guide the afternoon as much as the morning."],
  ["Midday, {name}.", "God is worth acknowledging in the middle of the day."],
  ["Noon has come, {name}.", "So has another opportunity to walk humbly with God."],
  ["Lunchtime, {name}.", "God sees every detail of this day — none of it is lost on Him."],
  ["Midday finds you, {name}.", "The Lord finds you worth His care."],
  ["The midday hour is here, {name}.", "Use the pause to give God thanks."],
  ["Noon, {name}.", "Christ is the bread of life — nourish your soul on Him."],
  ["Midday greets you, {name}.", "God's promises remain firm at noon."],
  ["The middle of the day, {name}.", "God's faithfulness holds the middle of every day together."],
  ["Lunchtime, {name}.", "A moment of gratitude at noon honors the Giver of all things."],
  ["Midday has arrived, {name}.", "Bring the rest of the day to God before it begins."],
  ["Noon is here, {name}.", "The Lord is the same God at noon that He was at sunrise."],
  ["The noon hour, {name}.", "Give God a moment before the afternoon takes the rest."],
];

const AFTERNOON: G[] = [
  ["The afternoon is here, {name}.", "Let your heart be refreshed by God's truth."],
  ["The day continues, {name}.", "Remember what matters most is eternal."],
  ["Good afternoon, {name}.", "Take a moment to be still before God."],
  ["The afternoon presses on, {name}.", "Walk in wisdom for the remaining hours."],
  ["The day is moving, {name}.", "God's purposes are moving with it."],
  ["Good afternoon, {name}.", "Cast your cares on God — He is able."],
  ["The afternoon is here, {name}.", "God's faithfulness spans the whole day."],
  ["The day is underway, {name}.", "Let every hour serve God's glory."],
  ["Good afternoon, {name}.", "Fix your thoughts on what is true and honorable."],
  ["The afternoon finds you, {name}.", "Find God in return."],
  ["The day moves along, {name}.", "God's purposes move with precision."],
  ["Good afternoon, {name}.", "Pray without ceasing — even in a busy afternoon."],
  ["The afternoon is here, {name}.", "Let gratitude settle into the hours ahead."],
  ["The day is in full stride, {name}.", "Walk in the Spirit through it."],
  ["Good afternoon, {name}.", "God does not change between morning and afternoon."],
  ["The afternoon is upon you, {name}.", "Consider how God has been faithful already today."],
  ["The day continues, {name}.", "God's patience and grace continue with it."],
  ["Good afternoon, {name}.", "Remember that you work for an audience of One."],
  ["The afternoon hours, {name}.", "God governs every one of them."],
  ["The day moves forward, {name}.", "Walk forward with God."],
  ["Good afternoon, {name}.", "Do not grow weary in doing good — God sees it."],
  ["The afternoon is here, {name}.", "Lift a brief prayer before the day rushes past."],
  ["The day is in motion, {name}.", "Keep your heart in motion toward God."],
  ["Good afternoon, {name}.", "God's sovereignty is a comfort in the busiest hours."],
  ["The afternoon is underway, {name}.", "Let wisdom govern every decision remaining today."],
  ["The day presses on, {name}.", "God's steadfast love presses through every hour."],
  ["Good afternoon, {name}.", "The Lord is worthy of your attention even now."],
  ["The afternoon continues, {name}.", "So does God's care for you."],
  ["The day is moving, {name}.", "God's truth is not moving — it is anchored."],
  ["Good afternoon, {name}.", "Ask God for patience — it is a fruit of the Spirit."],
  ["The afternoon is here, {name}.", "Let your heart be at rest in God."],
  ["The day is pushing along, {name}.", "Stay grounded in what is eternal."],
  ["Good afternoon, {name}.", "God's purposes are not hurried — neither should you be."],
  ["The afternoon finds you, {name}.", "The Lord has not lost sight of you."],
  ["The day continues, {name}.", "Walk humbly with God through every remaining hour."],
  ["Good afternoon, {name}.", "Scripture is worth reading even in the middle of a busy afternoon."],
  ["The afternoon is upon you, {name}.", "God's grace is upon you too — ask for it."],
  ["The day moves on, {name}.", "God's promises do not move — they are immovable."],
  ["Good afternoon, {name}.", "The King is on His throne — nothing today escapes His sight."],
  ["The afternoon is here, {name}.", "Give God a moment before the evening comes."],
  ["The day is at work, {name}.", "Work as unto the Lord."],
  ["Good afternoon, {name}.", "God's peace surpasses understanding — ask for it."],
  ["The afternoon presses, {name}.", "Press toward what is godly and good."],
  ["The day moves quickly, {name}.", "Eternity moves not at all — keep the eternal in view."],
  ["Good afternoon, {name}.", "God is near to those who call upon Him — call on Him now."],
  ["The afternoon is here, {name}.", "The Lord your God is with you — take courage."],
  ["The day is in the middle hours, {name}.", "God is in the middle of all things."],
  ["Good afternoon, {name}.", "Do your work with diligence — God rewards faithfulness."],
  ["The afternoon finds you, {name}.", "Let it find you walking in wisdom."],
  ["The day moves along, {name}.", "Keep your eyes on what is above."],
  ["Good afternoon, {name}.", "The Lord is the portion of those who seek Him."],
  ["The afternoon is here, {name}.", "A good time to pray for those around you."],
  ["The day is alive, {name}.", "Live it for God's glory."],
  ["Good afternoon, {name}.", "Let no unwholesome word come from your mouth — speak with grace."],
  ["The afternoon presses on, {name}.", "God's patience with us presses on too."],
  ["The day continues its work, {name}.", "God continues His work in you."],
  ["Good afternoon, {name}.", "Seek God's face — He promises to be found."],
  ["The afternoon is here, {name}.", "God's faithfulness holds the afternoon just as it held the morning."],
  ["The day moves forward, {name}.", "Move forward in the fear of the Lord."],
  ["Good afternoon, {name}.", "A humble heart is never too busy for God."],
  ["The afternoon finds you busy, {name}.", "Even busy hearts can turn briefly to prayer."],
  ["The day is full, {name}.", "Let it be full of God's glory too."],
  ["Good afternoon, {name}.", "The name of the Lord is a strong tower — run to it."],
  ["The afternoon is here, {name}.", "God's Word has not changed since this morning."],
  ["The day is progressing, {name}.", "Walk in the Spirit through every step."],
  ["Good afternoon, {name}.", "Ask for wisdom — God gives it generously."],
  ["The afternoon is moving, {name}.", "Move through it with gratitude and grace."],
  ["The day is still yours, {name}.", "Steward it well before it is gone."],
  ["Good afternoon, {name}.", "God's goodness is worth acknowledging in the afternoon hours."],
  ["The afternoon is here, {name}.", "Whatever the morning held, God was faithful through it."],
  ["The day continues its course, {name}.", "Walk the course God has set before you."],
  ["Good afternoon, {name}.", "Let your speech be kind and your heart be thankful."],
  ["The afternoon is upon you, {name}.", "God's care is upon you — rest in that."],
  ["The day moves on, {name}.", "The Word of God does not move — it stands forever."],
  ["Good afternoon, {name}.", "Repentance is always appropriate — and always welcome."],
  ["The afternoon continues, {name}.", "God's mercy continues with it."],
  ["The day is active, {name}.", "Keep your heart quietly active in prayer."],
  ["Good afternoon, {name}.", "God is not indifferent to the details of this day."],
  ["The afternoon is here, {name}.", "Let wisdom be your guide through the remaining hours."],
  ["The day is moving toward evening, {name}.", "Move toward God before the day is done."],
  ["Good afternoon, {name}.", "Consider the grace of God — it never runs dry."],
  ["The afternoon finds you, {name}.", "Let it find you trusting in God."],
  ["The day is winding through its hours, {name}.", "God winds through every one of them with you."],
  ["Good afternoon, {name}.", "The Lord sees your labor — do it as unto Him."],
  ["The afternoon is here, {name}.", "A good time to remember why you do what you do."],
  ["The day presses onward, {name}.", "Press onward toward what is true and good."],
  ["Good afternoon, {name}.", "God is faithful in the afternoon as He was in the morning."],
  ["The afternoon moves, {name}.", "Keep moving in the direction of wisdom."],
  ["The day is here, {name}.", "Make it count for what lasts beyond the day."],
  ["Good afternoon, {name}.", "Prayer in the afternoon keeps the soul steady."],
  ["The afternoon is here, {name}.", "Give God the rest of the day — He will make good use of it."],
  ["The day is heading toward its close, {name}.", "Give God the close as well as the opening."],
  ["Good afternoon, {name}.", "The Lord's purposes are running on time — trust them."],
  ["The afternoon presses, {name}.", "God does not press — He leads. Follow Him."],
  ["The day is still going, {name}.", "So is God's faithfulness."],
  ["Good afternoon, {name}.", "Let the afternoon be as intentional as the morning began."],
  ["The afternoon is here, {name}.", "God's grace is more than enough for the rest of this day."],
];

const EVENING: G[] = [
  ["The evening has arrived, {name}.", "Reflect on the Lord's goodness today."],
  ["The day is slowing down, {name}.", "Give thanks for God's faithfulness."],
  ["Good evening, {name}.", "The Lord has been faithful through every hour."],
  ["The evening is here, {name}.", "Bring your day to God in prayer."],
  ["The day is winding down, {name}.", "Let your heart wind down in gratitude."],
  ["Good evening, {name}.", "Count the mercies from this day — they are more than you know."],
  ["The evening has come, {name}.", "God was faithful through every hour of the day."],
  ["The day is nearly done, {name}.", "The Lord is not nearly done with His care for you."],
  ["Good evening, {name}.", "Reflect on what God has done and give thanks."],
  ["The evening is settling in, {name}.", "Settle your heart in the Lord."],
  ["The day draws to a close, {name}.", "God's faithfulness does not."],
  ["Good evening, {name}.", "The evening is a good time to open the Scriptures."],
  ["The evening light is here, {name}.", "Christ is the Light the darkness cannot overcome."],
  ["The day is coming to an end, {name}.", "God's purposes are not."],
  ["Good evening, {name}.", "Give thanks before the day is fully gone."],
  ["The evening has arrived, {name}.", "God has kept you through another day."],
  ["The day is settling, {name}.", "Let your soul settle in God's unchanging character."],
  ["Good evening, {name}.", "Pray tonight for those you love and those you find difficult."],
  ["The evening is here, {name}.", "A good time to confess and give thanks."],
  ["The day is behind you, {name}.", "God was present in every moment of it."],
  ["Good evening, {name}.", "The Lord reigns through the evening as He did through the morning."],
  ["The evening comes, {name}.", "Come to God before the night does."],
  ["The day is closing, {name}.", "Close it with prayer and gratitude."],
  ["Good evening, {name}.", "God's steadfast love endures — morning and evening alike."],
  ["The evening is settling around you, {name}.", "Let the peace of God settle in you."],
  ["The day has run its course, {name}.", "Entrust the outcome to God."],
  ["Good evening, {name}.", "Repent of what the day held that was not good — and rest."],
  ["The evening is here, {name}.", "The Lord saw every moment of this day — nothing was wasted."],
  ["The day is nearly gone, {name}.", "God's care is not nearly gone — it is eternal."],
  ["Good evening, {name}.", "Bring what the day has left unresolved to God."],
  ["The evening arrives, {name}.", "God arrived before you did — He is already here."],
  ["The day is quieting, {name}.", "Let your heart quiet before God."],
  ["Good evening, {name}.", "Consider how God was present in the details of today."],
  ["The evening is upon you, {name}.", "God's purposes are upon the whole earth — and upon you."],
  ["The day has been given, {name}.", "Give it back to God in thanks."],
  ["Good evening, {name}.", "The Lord's mercies await the morning — rest in that."],
  ["The evening settles in, {name}.", "Settle your heart in the goodness of God."],
  ["The day is winding down, {name}.", "God is winding nothing down — He is always at work."],
  ["Good evening, {name}.", "A good evening begins with a prayer of thanks."],
  ["The evening is here, {name}.", "Let the Scriptures accompany you into the night."],
  ["The day is drawing to its end, {name}.", "Draw near to God before it does."],
  ["Good evening, {name}.", "God's faithfulness today is not separate from His faithfulness tomorrow."],
  ["The evening has come, {name}.", "Come to Christ — He says He will not cast away any who come."],
  ["The day is done, {name}.", "God is never done with His purposes for you."],
  ["Good evening, {name}.", "Give the anxieties of the day to God before they follow you into sleep."],
  ["The evening is here, {name}.", "Rest is a gift from God — receive it gratefully."],
  ["The day is ending, {name}.", "God's love is not ending — it is everlasting."],
  ["Good evening, {name}.", "Reflect on God's goodness before the night takes over."],
  ["The evening settles, {name}.", "God does not settle — He never sleeps."],
  ["The day has been full, {name}.", "God's grace was fuller."],
  ["Good evening, {name}.", "Let gratitude be the last significant thought of the day."],
  ["The evening arrives gently, {name}.", "God arrives in every season — gentle and sovereign."],
  ["The day is behind you, {name}.", "Entrust it to God and look forward to His mercies tomorrow."],
  ["Good evening, {name}.", "The Lord's presence does not diminish at evening."],
  ["The evening is here, {name}.", "A brief prayer before the night is always well spent."],
  ["The day has served its purpose, {name}.", "Give thanks for every part of it."],
  ["Good evening, {name}.", "Christ is the same at evening as He was at morning."],
  ["The evening finds you, {name}.", "May it find you resting in God's care."],
  ["The day is finishing, {name}.", "God is not finishing — His purposes run eternal."],
  ["Good evening, {name}.", "Pray for the night — that it would be restful and God-honoring."],
  ["The evening is here, {name}.", "The Lord has governed this day well — trust Him with tonight."],
  ["The day draws to a quiet close, {name}.", "Let your heart close quietly in gratitude."],
  ["Good evening, {name}.", "God's Word is worth a few minutes even at the close of the day."],
  ["The evening settles in around you, {name}.", "God's sovereignty settles over all things."],
  ["The day is winding to its end, {name}.", "Wind your heart toward God before it does."],
  ["Good evening, {name}.", "Nothing from today has escaped God's notice or His care."],
  ["The evening is here, {name}.", "Consider how God met you in this day."],
  ["The day is nearly finished, {name}.", "The Lord who began it is also finishing it."],
  ["Good evening, {name}.", "A thankful heart rests well."],
  ["The evening comes quietly, {name}.", "Come quietly to God before the night."],
  ["The day closes, {name}.", "God does not close — He is always present."],
  ["Good evening, {name}.", "Give the unfinished things of today to God."],
  ["The evening is upon you, {name}.", "God's faithfulness is upon you too — it is His character."],
  ["The day ends, {name}.", "God does not end — He is from everlasting to everlasting."],
  ["Good evening, {name}.", "Repentance and rest make a good evening."],
  ["The evening arrives, {name}.", "God arrived in this world at the incarnation — He is with us."],
  ["The day is done, {name}.", "Give God what the day has left."],
  ["Good evening, {name}.", "Let the peace of God guard your heart tonight."],
  ["The evening settles, {name}.", "God is settled — He never changes."],
  ["The day has been given, {name}.", "Return it to God with thanks."],
  ["Good evening, {name}.", "The Lord is a refuge for the evening as for every hour."],
  ["The evening is here, {name}.", "Draw near to God before sleep draws near."],
  ["The day has run, {name}.", "God has run beside you through every step."],
  ["Good evening, {name}.", "Let Scripture be the last thing you read before sleep."],
  ["The evening is upon you, {name}.", "God's goodness has been upon you all day — give thanks."],
  ["The day concludes, {name}.", "God's faithfulness does not conclude — it endures forever."],
  ["Good evening, {name}.", "Tomorrow's mercies are waiting — rest well tonight."],
  ["The evening is here, {name}.", "God's promises are as firm at evening as they were at dawn."],
  ["The day is ending, {name}.", "God's steadfast love is not ending — it runs to eternity."],
  ["Good evening, {name}.", "A prayer of thanks tonight is a good ending to any day."],
  ["The evening settles in, {name}.", "Let your soul settle on the character of God."],
  ["The day is nearly over, {name}.", "God's mercy over you is never nearly over."],
  ["Good evening, {name}.", "Bring the weight of the day to God — He invites the heavy-laden."],
  ["The evening is quietly here, {name}.", "Meet it with a quiet heart before God."],
  ["The day ends, {name}.", "God's love does not — it is new every morning."],
  ["Good evening, {name}.", "Give thanks for this day — it was a gift."],
];

const NIGHT: G[] = [
  ["Rest well tonight, {name}.", "Tomorrow's concerns belong to the Lord."],
  ["The day is ending, {name}.", "Give thanks for the mercies you've received."],
  ["Good night, {name}.", "The Lord reigns through every hour."],
  ["Before sleep, {name}.", "Remember the goodness of God."],
  ["The night is here, {name}.", "God keeps watch through every dark hour."],
  ["Good night, {name}.", "The Lord neither slumbers nor sleeps."],
  ["The evening grows late, {name}.", "Let your heart rest in God's unchanging care."],
  ["The night has come, {name}.", "God has not gone anywhere."],
  ["Rest well, {name}.", "God's purposes continue through the night."],
  ["Good night, {name}.", "Give the unresolved things to God before you sleep."],
  ["The night is here, {name}.", "God's faithfulness does not sleep."],
  ["Rest is coming, {name}.", "The God who gives rest is worthy of thanks."],
  ["Good night, {name}.", "Lay down your burdens — God can carry them through the night."],
  ["The day has ended, {name}.", "God's steadfast love has not ended."],
  ["Good night, {name}.", "A prayer before sleep is always a good last act."],
  ["The night settles in, {name}.", "Settle your soul in the Lord."],
  ["Rest well tonight, {name}.", "God is still working while you sleep."],
  ["Good night, {name}.", "The Lord's promises are as firm in the night as in the day."],
  ["The night is upon you, {name}.", "God is upon all things — rest in that."],
  ["Sleep well, {name}.", "God guards those who trust in Him."],
  ["Good night, {name}.", "Consider one thing God did for you today and give thanks."],
  ["The night is here, {name}.", "God's Word is a lamp — even in the dark."],
  ["Rest tonight, {name}.", "God does not need your help to sustain the world."],
  ["Good night, {name}.", "Tomorrow is in God's hands — give it to Him now."],
  ["The night is settling, {name}.", "Let your heart settle in the peace of God."],
  ["Rest well, {name}.", "Repentance before sleep keeps the heart clean."],
  ["Good night, {name}.", "God's care for you runs through the darkest hours."],
  ["The night arrives, {name}.", "God arrived before it — He is already present."],
  ["Sleep comes, {name}.", "Give thanks before it does."],
  ["Good night, {name}.", "The Lord is a shield around those who trust in Him."],
  ["The night is here, {name}.", "Rest is a gift from God — receive it with gratitude."],
  ["Rest well tonight, {name}.", "God sees you through every hour of the night."],
  ["Good night, {name}.", "Pray briefly before you sleep — God hears every sincere prayer."],
  ["The night has arrived, {name}.", "God's faithfulness has arrived alongside it."],
  ["Rest is near, {name}.", "The God who never rests gives rest to His creatures."],
  ["Good night, {name}.", "Let gratitude be your last waking thought."],
  ["The night settles over the world, {name}.", "God's sovereignty settles over all of it."],
  ["Sleep well, {name}.", "God's purposes move forward even as you rest."],
  ["Good night, {name}.", "The night holds no surprises for God."],
  ["The night is here, {name}.", "Cast your remaining anxieties on God before you sleep."],
  ["Rest well, {name}.", "God's Word is worth a few minutes before the night takes you."],
  ["Good night, {name}.", "The Lord is the same tonight as He was this morning."],
  ["The night has come, {name}.", "Come to God in prayer before sleep."],
  ["Sleep in peace, {name}.", "God guards those who rest in Him."],
  ["Good night, {name}.", "Tomorrow's mercies are ready and waiting."],
  ["The night settles in, {name}.", "God does not settle — He keeps watch."],
  ["Rest well tonight, {name}.", "God has been faithful today and He will be faithful tomorrow."],
  ["Good night, {name}.", "Let Scripture accompany you into sleep."],
  ["The night is here, {name}.", "Christ is the Light no darkness can overcome — rest in that."],
  ["Sleep comes, {name}.", "God's grace carries you through the night."],
  ["Good night, {name}.", "Give thanks before the day is entirely gone."],
  ["The night draws in, {name}.", "Draw near to God before you sleep."],
  ["Rest well, {name}.", "God's promises are as true at night as at noon."],
  ["Good night, {name}.", "The Lord is a refuge — take shelter in Him tonight."],
  ["The night has settled, {name}.", "Let your soul settle on the goodness of God."],
  ["Sleep well tonight, {name}.", "God watches over those who trust in Him."],
  ["Good night, {name}.", "Nothing from today has escaped God's attention."],
  ["The night is here, {name}.", "Entrust the night to God as you entrust the day."],
  ["Rest is here, {name}.", "Receive it with gratitude — God gives rest to those He loves."],
  ["Good night, {name}.", "Tomorrow is already known to God — rest well."],
  ["The night settles quietly, {name}.", "Let your heart settle quietly in God."],
  ["Sleep well, {name}.", "God's care for you does not clock out for the night."],
  ["Good night, {name}.", "A thankful heart is the best preparation for sleep."],
  ["The night is upon you, {name}.", "God is upon all things — you are not beyond His reach."],
  ["Rest tonight, {name}.", "God's faithfulness will greet you in the morning."],
  ["Good night, {name}.", "Repent, give thanks, and sleep — all three are wise."],
  ["The night arrives softly, {name}.", "God arrives in every season of life."],
  ["Sleep well, {name}.", "God's Word is worth reading even before sleep."],
  ["Good night, {name}.", "The Lord keeps your coming and your going — even your sleeping."],
  ["The night is here, {name}.", "God's steadfast love runs through every dark hour."],
  ["Rest well tonight, {name}.", "What you could not finish today, God can carry."],
  ["Good night, {name}.", "Pray for tomorrow before it arrives."],
  ["The night settles in, {name}.", "God is settled — He never wavers or changes."],
  ["Sleep comes quietly, {name}.", "Let your soul come quietly to God before it does."],
  ["Good night, {name}.", "God's purposes are not resting tonight."],
  ["The night is here, {name}.", "Let the night be a reminder — God governs the darkness too."],
  ["Rest well, {name}.", "Every good gift comes from above — including sleep."],
  ["Good night, {name}.", "The Lord's counsel is worth seeking before the next day begins."],
  ["The night has come, {name}.", "Come to God with whatever remains."],
  ["Sleep in peace, {name}.", "God's peace surpasses understanding — ask for it."],
  ["Good night, {name}.", "God will not abandon what He has begun."],
  ["The night settles around you, {name}.", "God's love settles over you — it is not moved by the hour."],
  ["Rest well tonight, {name}.", "The Lord holds the night in His hands."],
  ["Good night, {name}.", "A brief prayer now is a good way to close the day."],
  ["The night is upon you, {name}.", "Let gratitude be the final note before rest."],
  ["Sleep well, {name}.", "God's faithfulness is not diminished by the night."],
  ["Good night, {name}.", "Whatever the day held, God was in every moment of it."],
  ["The night arrives, {name}.", "God is always arriving — He is omnipresent."],
  ["Rest well, {name}.", "Tomorrow holds God's mercies — they will be new."],
  ["Good night, {name}.", "Let the last thought be a thought of thanksgiving."],
  ["The night is settling in, {name}.", "Settle in the unchanging character of God."],
  ["Sleep comes, {name}.", "God never sleeps — rest in that tonight."],
  ["Good night, {name}.", "The darkness is not dark to God — rest without fear."],
  ["The night is here, {name}.", "God's love holds you through every hour of it."],
  ["Rest well, {name}.", "God's mercies will be new when you wake."],
  ["Good night, {name}.", "Close the day with prayer and open tomorrow the same way."],
  ["The night settles, {name}.", "God's truth settles nothing — it stands firm forever."],
  ["Sleep well tonight, {name}.", "God is sovereign over your sleep and your waking."],
  ["Good night, {name}.", "The Lord is worthy of the last moments of this day."],
];

const LATE_NIGHT: G[] = [
  ["You're up late, {name}.", "The Lord's truth remains unchanged through every hour."],
  ["The night is quiet, {name}.", "God's promises still stand."],
  ["A new day is drawing near, {name}.", "The Lord remains faithful."],
  ["The late hours find you awake, {name}.", "God has been awake through every hour."],
  ["You are awake late, {name}.", "The Lord never slumbers — you are not alone."],
  ["The night is deep, {name}.", "God's presence is deeper."],
  ["Late night, {name}.", "God's Word is a lamp even in the dark hours."],
  ["The world is quiet now, {name}.", "God is not quiet — He is always at work."],
  ["A late hour, {name}.", "God's purposes do not sleep."],
  ["You're still awake, {name}.", "The Lord who made the night is near."],
  ["The night stretches on, {name}.", "God's steadfast love stretches further."],
  ["Late into the night, {name}.", "God's faithfulness holds through every dark hour."],
  ["The quiet of the night, {name}.", "God speaks in the still, small voice — listen."],
  ["A late hour is upon you, {name}.", "Cast your cares on God before sleep takes you."],
  ["The night is still, {name}.", "God is never still — He is always at work."],
  ["You are awake in the late hours, {name}.", "So is the Lord."],
  ["Late night, {name}.", "Bring whatever keeps you awake to the Lord in prayer."],
  ["The night runs on, {name}.", "God's sovereignty runs further."],
  ["A quiet night, {name}.", "God fills every quiet moment with His presence."],
  ["You're up late, {name}.", "God's love for you has not diminished with the hour."],
  ["The darkness is deep, {name}.", "Christ is the Light no darkness can overcome."],
  ["A late hour, {name}.", "The Lord hears prayers at every hour."],
  ["The night is long, {name}.", "God's patience is longer."],
  ["Late night finds you, {name}.", "God found you before you were looking for Him."],
  ["You are awake, {name}.", "God has kept watch all along."],
  ["The night is here, {name}.", "Tomorrow's mercies are already prepared."],
  ["Late night, {name}.", "Consider what the Lord has done — praise is fitting at any hour."],
  ["The quiet hours find you, {name}.", "Use the quiet to bring your heart before God."],
  ["A late hour, {name}.", "Prayer at midnight is just as heard as prayer at noon."],
  ["The night is deep, {name}.", "God's wisdom is deeper — seek it."],
  ["You are awake late, {name}.", "The Lord's Word is worth reading even now."],
  ["Late night is here, {name}.", "God's faithfulness runs through every dark hour."],
  ["The night stretches out, {name}.", "God's mercy stretches out further — to eternity."],
  ["A late and quiet hour, {name}.", "Bring a quiet heart before a great God."],
  ["The world sleeps, {name}.", "God does not — He never slumbers."],
  ["Late into the night, {name}.", "God's purposes are not on hold."],
  ["You're still up, {name}.", "The Lord is still present — He always is."],
  ["The night is quiet around you, {name}.", "Let your heart be quiet before God."],
  ["A late hour finds you, {name}.", "God has kept watch since the very first moment."],
  ["The night runs deep, {name}.", "God's love runs deeper."],
  ["You are awake in the dark hours, {name}.", "The darkness is not dark to God."],
  ["Late night, {name}.", "Rest is coming — and it is a gift from the Lord."],
  ["The night holds you, {name}.", "God's hands hold the night."],
  ["A quiet hour, {name}.", "God is not quiet — He speaks through Scripture."],
  ["You're up late, {name}.", "Whatever keeps you awake, God already knows."],
  ["The late night is here, {name}.", "God's truth is just as firm in the dark."],
  ["Late into the night, {name}.", "The Lord's compassions never fail — not even now."],
  ["The night is long, {name}.", "God's faithfulness is longer."],
  ["A late hour, {name}.", "Bring your heart before God — He hears at every hour."],
  ["You are awake, {name}.", "God is with you in the late and quiet hours."],
  ["The night is deep around you, {name}.", "God's presence surrounds you."],
  ["Late night, {name}.", "Sleep is a gift from God — receive it when it comes."],
  ["The quiet of the night surrounds you, {name}.", "Let it draw you to prayer."],
  ["A late hour finds you awake, {name}.", "God is awake with you."],
  ["The night stretches on, {name}.", "God's purposes stretch beyond the night."],
  ["You're up late, {name}.", "Cast your anxieties on God — He is able to carry them."],
  ["Late night is here, {name}.", "Nothing about this hour is outside God's knowledge."],
  ["The night is quiet and dark, {name}.", "God's light shines through the darkest hours."],
  ["A late and still hour, {name}.", "Be still and know that He is God."],
  ["The night continues, {name}.", "God's care continues with it."],
  ["You are awake late, {name}.", "Turn your thoughts to what is true — God's Word remains."],
  ["Late night, {name}.", "God's promises do not expire with the late hours."],
  ["The night is here in full, {name}.", "God's faithfulness is here in full too."],
  ["A late hour, {name}.", "Pray before sleep — God hears every sincere prayer."],
  ["The night is long and still, {name}.", "God fills every long night with His presence."],
  ["You're awake late, {name}.", "The Lord of the night is near."],
  ["Late into the quiet night, {name}.", "God's Word is worth a moment before rest."],
  ["The darkness holds the late hour, {name}.", "God holds the darkness."],
  ["A late night, {name}.", "Rest will come — and with it, new mercies."],
  ["The night is quiet around you, {name}.", "Quiet your heart and give thanks."],
  ["Late night is here, {name}.", "Whatever weighs on you, God can carry it."],
  ["You are up late, {name}.", "The Lord who made the stars is watching over you."],
  ["The late hour is quiet, {name}.", "Use the quiet to remember who God is."],
  ["A late night finds you, {name}.", "God finds you wherever you are."],
  ["The night is deep, {name}.", "God is deeper still."],
  ["Late night, {name}.", "The Lord's faithfulness runs through every unseen hour."],
  ["You're awake, {name}.", "God keeps watch — you are not alone in this hour."],
  ["The night stretches quietly on, {name}.", "God stretches His care over every part of it."],
  ["A late hour, {name}.", "Bring your heart to God before sleep takes you."],
  ["The night is here, {name}.", "God's purposes are at work even in the dark."],
  ["Late night is upon you, {name}.", "God's love is upon you — through every hour."],
  ["The quiet night surrounds you, {name}.", "God's presence is quieter — but present."],
  ["You are awake late, {name}.", "The Lord hears the prayers of the sleepless."],
  ["Late night, {name}.", "Whatever tomorrow holds, God has already seen it."],
  ["The darkness of the night, {name}.", "God is not in the dark about your situation."],
  ["A late and quiet hour, {name}.", "Let gratitude be the last thought before sleep."],
  ["The night continues, {name}.", "God's faithfulness continues with it."],
  ["Late night finds you awake, {name}.", "Find God in the waking hours as well as the day."],
  ["The night is here, {name}.", "God reigns through every hour — even this one."],
  ["A late hour, {name}.", "Rest is a gift — receive it in gratitude when it comes."],
  ["You're up late, {name}.", "The Lord's truth is as firm at midnight as at noon."],
  ["The night stretches on, {name}.", "God's love stretches to eternity."],
  ["Late into the night, {name}.", "The Lord is near to all who call upon Him — even now."],
  ["The night is deep, {name}.", "God's wisdom runs deeper — seek it in Scripture."],
  ["A quiet late night, {name}.", "Give God the final moments before sleep."],
  ["Late night is here, {name}.", "Sleep is coming — and God's mercies will greet the morning."],
  ["You are awake in the night, {name}.", "God has been awake through every moment of it."],
];

// ─── Spanish pool (kept for Spanish mode) ────────────────────────────────────
export interface Greeting {
  line1: string;
  line2: string;
  line1Es?: string;
  line2Es?: string;
  slot: "morning" | "afternoon" | "evening" | "night" | "any";
}

export const GREETINGS: Greeting[] = [
  { slot: "morning",   line1: "Good morning, {name}.", line2: "God's mercies are new every morning.", line1Es: "Buenos días, {name}.", line2Es: "Las misericordias de Dios son nuevas cada mañana." },
  { slot: "morning",   line1: "A new day begins, {name}.", line2: "Seek the Lord while He may be found.", line1Es: "Un nuevo día comienza, {name}.", line2Es: "Busca al Señor mientras puede ser hallado." },
  { slot: "morning",   line1: "Rise with gratitude, {name}.", line2: "The Lord has given you another day.", line1Es: "Despierta con gratitud, {name}.", line2Es: "El Señor te ha dado un día más." },
  { slot: "morning",   line1: "The morning is a gift, {name}.", line2: "Seek first the kingdom of God.", line1Es: "La mañana es un regalo, {name}.", line2Es: "Busca primero el reino de Dios." },
  { slot: "morning",   line1: "Good morning, {name}.", line2: "Open the Word — God still speaks.", line1Es: "Buenos días, {name}.", line2Es: "Abre la Palabra — Dios aún habla." },
  { slot: "morning",   line1: "The sun is rising, {name}.", line2: "God's faithfulness rises with it.", line1Es: "El sol sale, {name}.", line2Es: "La fidelidad de Dios sale con él." },
  { slot: "morning",   line1: "Another sunrise, {name}.", line2: "Another reminder of God's faithfulness.", line1Es: "Otro amanecer, {name}.", line2Es: "Otro recordatorio de la fidelidad de Dios." },
  { slot: "morning",   line1: "Good morning, {name}.", line2: "The fear of the Lord is the beginning of wisdom.", line1Es: "Buenos días, {name}.", line2Es: "El temor del Señor es el principio de la sabiduría." },
  { slot: "morning",   line1: "A new morning, {name}.", line2: "Walk humbly with your God today.", line1Es: "Una nueva mañana, {name}.", line2Es: "Camina humildemente con tu Dios hoy." },
  { slot: "morning",   line1: "Good morning, {name}.", line2: "Pray before the day fills your mind with noise.", line1Es: "Buenos días, {name}.", line2Es: "Ora antes de que el día llene tu mente de ruido." },
  { slot: "afternoon", line1: "Good afternoon, {name}.", line2: "God's grace is sufficient for every moment.", line1Es: "Buenas tardes, {name}.", line2Es: "La gracia de Dios es suficiente para cada momento." },
  { slot: "afternoon", line1: "The afternoon is here, {name}.", line2: "Let your thoughts return to Christ.", line1Es: "La tarde ha llegado, {name}.", line2Es: "Que tus pensamientos vuelvan a Cristo." },
  { slot: "afternoon", line1: "Pause for a moment, {name}.", line2: "God sees every detail of your day.", line1Es: "Pausa un momento, {name}.", line2Es: "Dios ve cada detalle de tu día." },
  { slot: "afternoon", line1: "The day moves quickly, {name}.", line2: "Keep your eyes on what is eternal.", line1Es: "El día pasa rápido, {name}.", line2Es: "Mantén los ojos en lo eterno." },
  { slot: "afternoon", line1: "Good afternoon, {name}.", line2: "Cast your cares on God — He is able.", line1Es: "Buenas tardes, {name}.", line2Es: "Echa tus cargas sobre Dios — Él puede llevarlas." },
  { slot: "afternoon", line1: "The afternoon presses on, {name}.", line2: "Walk in wisdom for the remaining hours.", line1Es: "La tarde avanza, {name}.", line2Es: "Camina en sabiduría en las horas que quedan." },
  { slot: "afternoon", line1: "The day continues, {name}.", line2: "God's faithfulness continues with it.", line1Es: "El día continúa, {name}.", line2Es: "La fidelidad de Dios continúa con él." },
  { slot: "afternoon", line1: "Good afternoon, {name}.", line2: "Pray without ceasing — even in a busy afternoon.", line1Es: "Buenas tardes, {name}.", line2Es: "Ora sin cesar — incluso en una tarde ajetreada." },
  { slot: "evening",   line1: "Good evening, {name}.", line2: "Reflect on the Lord's goodness today.", line1Es: "Buenas noches, {name}.", line2Es: "Reflexiona en la bondad del Señor hoy." },
  { slot: "evening",   line1: "The day is ending, {name}.", line2: "Christ remains the Light of the world.", line1Es: "El día termina, {name}.", line2Es: "Cristo sigue siendo la Luz del mundo." },
  { slot: "evening",   line1: "The evening is here, {name}.", line2: "Bring your day to God in prayer.", line1Es: "La noche ha llegado, {name}.", line2Es: "Lleva tu día a Dios en oración." },
  { slot: "evening",   line1: "The day is done, {name}.", line2: "His mercies await tomorrow.", line1Es: "El día ha terminado, {name}.", line2Es: "Sus misericordias esperan mañana." },
  { slot: "evening",   line1: "Good evening, {name}.", line2: "God was faithful through every hour.", line1Es: "Buenas noches, {name}.", line2Es: "Dios fue fiel en cada hora." },
  { slot: "evening",   line1: "The evening settles in, {name}.", line2: "Let your heart settle in God's unchanging care.", line1Es: "La noche llega, {name}.", line2Es: "Deja que tu corazón descanse en el cuidado inmutable de Dios." },
  { slot: "evening",   line1: "Another day is finished, {name}.", line2: "Give thanks for God's faithfulness.", line1Es: "Otro día ha terminado, {name}.", line2Es: "Da gracias por la fidelidad de Dios." },
  { slot: "evening",   line1: "Good evening, {name}.", line2: "Let gratitude be the last note of the day.", line1Es: "Buenas noches, {name}.", line2Es: "Que la gratitud sea la última nota del día." },
  { slot: "night",     line1: "Rest well, {name}.", line2: "The Lord never slumbers nor sleeps.", line1Es: "Que descanses, {name}.", line2Es: "El Señor no dormita ni duerme." },
  { slot: "night",     line1: "Good night, {name}.", line2: "The Lord reigns through every hour.", line1Es: "Buenas noches, {name}.", line2Es: "El Señor reina en cada hora." },
  { slot: "night",     line1: "Sleep well, {name}.", line2: "God's care does not stop for the night.", line1Es: "Duerme bien, {name}.", line2Es: "El cuidado de Dios no se detiene por la noche." },
  { slot: "night",     line1: "Rest tonight, {name}.", line2: "Tomorrow's mercies are already prepared.", line1Es: "Descansa esta noche, {name}.", line2Es: "Las misericordias de mañana ya están preparadas." },
  { slot: "any",       line1: "God's Word stands forever, {name}.", line2: "Build your life upon it.", line1Es: "La Palabra de Dios permanece para siempre, {name}.", line2Es: "Edifica tu vida sobre ella." },
  { slot: "any",       line1: "The Lord is mighty to save, {name}.", line2: "Call upon Him while He may be found.", line1Es: "El Señor es poderoso para salvar, {name}.", line2Es: "Invócalo mientras puede ser hallado." },
  { slot: "any",       line1: "Christ is sufficient, {name}.", line2: "He has always been sufficient.", line1Es: "Cristo es suficiente, {name}.", line2Es: "Siempre ha sido suficiente." },
  { slot: "any",       line1: "Nothing surprises God today, {name}.", line2: "Walk in quiet trust.", line1Es: "Nada sorprende a Dios hoy, {name}.", line2Es: "Camina con confianza tranquila." },
  { slot: "any",       line1: "Look to the cross, {name}.", line2: "There is fullness of mercy there.", line1Es: "Mira la cruz, {name}.", line2Es: "Allí hay plena misericordia." },
];

// ─── Seeded random ────────────────────────────────────────────────────────────
function hashCode(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(31, h) + str.charCodeAt(i) | 0;
  }
  return Math.abs(h);
}

function pickFromPool(pool: G[], seed: number): G {
  return pool[seed % pool.length];
}

// ─── Main export ──────────────────────────────────────────────────────────────
export function getDailyGreeting(name: string, hour: number, lang: string): { line1: string; line2: string } {
  const today     = new Date();
  const epoch     = new Date(2024, 0, 1);
  const daysSince = Math.floor((today.getTime() - epoch.getTime()) / (1000 * 60 * 60 * 24));
  const nameSeed  = name ? hashCode(name) : 0;
  const seed      = (daysSince * 397 + nameSeed) >>> 0;

  // ── Spanish mode: use existing GREETINGS pool ──────────────────────────────
  if (lang === "es") {
    const esSlot: Greeting["slot"] =
      hour >= 5  && hour < 12 ? "morning" :
      hour >= 12 && hour < 18 ? "afternoon" :
      hour >= 18 && hour < 22 ? "evening" : "night";
    const pool = GREETINGS.filter((g) => g.slot === esSlot || g.slot === "any");
    const pick = pool[seed % pool.length];
    const displayName = name.split(" ")[0];
    return {
      line1: (pick.line1Es ?? pick.line1).replace("{name}", displayName),
      line2: pick.line2Es ?? pick.line2,
    };
  }

  // ── English mode: 8-slot system ───────────────────────────────────────────
  let pool: G[];
  if      (hour >= 5  && hour < 8)  pool = EARLY_MORNING;
  else if (hour >= 8  && hour < 11) pool = MORNING;
  else if (hour === 11)             pool = LATE_MORNING;
  else if (hour >= 12 && hour < 14) pool = MIDDAY;
  else if (hour >= 14 && hour < 17) pool = AFTERNOON;
  else if (hour >= 17 && hour < 21) pool = EVENING;
  else if (hour >= 21)              pool = NIGHT;
  else                              pool = LATE_NIGHT; // 0–4

  const picked = pickFromPool(pool, seed);
  const displayName = name ? name.split(" ")[0] : "";
  return {
    line1: displayName
      ? picked[0].replace("{name}", displayName)
      : picked[0].replace(", {name}", "").replace(" {name}", ""),
    line2: picked[1],
  };
}
